name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Build with Gradle Wrapper
      run: ./gradlew build

    - name: Docker Build and Push  # ✅ Corrected step
      uses: docker/build-push-action@v5  # ✅ Use official action
      env:
        DOCKER_USER: ${{ secrets.MY_USER }}
        DOCKER_PASS: ${{ secrets.MY_PASSWORD }}
      with:
        context: .
        push: true
        tags: ${{ secrets.MY_USER }}/my-java-app:latest
        username: $DOCKER_USER
        password: $DOCKER_PASS

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@v4
