name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Configure Gradle for optimal use in GitHub Actions, including caching dependencies.
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4.0.0  # ✅ Updated to proper version reference

      - name: Build with Gradle Wrapper
        run: ./gradlew build

      - name: Docker Build and Push
        uses: mishu22bd/lab2githubactions  # ✅ Ensure this action exists in GitH
